---

ollama_url: http://localhost:11434
log_level: INFO
http_timeout: 30.0

commands:
  - exit:
      - /exit
      - /quit
      - /bye
  - reset:
      - /reset

default_system_prompt: Provide detailed and comprehensive response

# Model selection (names required, prompts optional)
models:
  - deepseek-r1:1.5b:
      system_prompt: Respond naturally and professionally
  - gemma3:1b:
      system_prompt: Respond naturally and professionally
  - SpeakLeash/bielik-11b-v2.3-instruct:Q4_K_M:
      system_prompt: Respond naturally and professionally
      judge: true
  - qwen3:0.6b:
      system_prompt: Respond naturally and professionally
  - phi4:latest:
      system_prompt: Respond naturally and professionally
      judge: true

judge:
  user_question_prefix: 'User question:'
  model_responses_prefix: 'Model responses:'
  model_response_format: |-
    Model {model_name} response:
    {response_content}
  response_format:
    header: 'Response format:'
    points:
      - Conduct an evaluation of the responses.
      - |-
        If necessary, provide an improved version of the response.
        When improving responses, take into account all provided correct answers.
      - |-
        Each evaluation should include the following:
        A rating of the answer's correctness (on a scale from 0 to 100), where 100 indicates a high degree of accuracy.
        A rating of the answer's overall quality (on a scale from 0 to 100), where 100 indicates exceptional quality.
        Quality rating should not exceed correctness rating.
        A concise written assessment of the response.
