---

ollama_url: http://localhost:11434
log_level: INFO
http_timeout: 300.0

commands:
  - exit:
      - /exit
      - /quit
      - /bye
  - reset:
      - /reset

default_system_prompt: Provide detailed and comprehensive response

# NAME                                          SIZE     JUDGE
# deepseek-r1:14b                               9.0 GB   +
# gemma3:4b                                     3.3 GB   +
# SpeakLeash/bielik-11b-v2.3-instruct:Q4_K_M    6.7 GB   +
# qwen3:14b                                     9.3 GB   +
# phi4:latest                                   9.1 GB   +

# Model selection (names required, prompts optional)
models:
  - deepseek-r1:14b:
      judge: true
  - gemma3:4b:
      judge: true
  - SpeakLeash/bielik-11b-v2.3-instruct:Q4_K_M:
      judge: true
  - qwen3:14b:
      judge: true
  - phi4:latest:
      judge: true

judge:
  user_question_prefix: 'User question:'
  model_responses_prefix: 'Model responses:'
  model_response_format: |-
    Model {model_name} response:
    {response_content}
  response_format:
    header: 'Response format:'
    points:
      - Conduct an evaluation of the responses.
      - |-
        If necessary, provide an improved version of the response.
        When improving responses, take into account all provided correct answers.
      - |-
        Each evaluation should include the following:
        A rating of the answer's correctness (on a scale from 0 to 100), where 100 indicates a high degree of accuracy.
        A rating of the answer's overall quality (on a scale from 0 to 100), where 100 indicates exceptional quality.
        Quality rating should not exceed correctness rating.
        A concise written assessment of the response.
